name: my_first_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  cupertino_icons: ^1.0.8
  animated_background: any
  glassmorphism_ui: any
  audioplayers: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/affirmations.jpg
    - assets/meditation.jpg
    - assets/videos/background.mp4
    - assets/videos/background1.mp4
    - assets/audio/calm_music.mp3
    
